#!/bin/sh

set -e

if [ "$1" = "upgrade" ]; then
  # Remove older deprecated themes. Can be removed post Zorin OS 16
  if dpkg --compare-versions "$2" lt-nl 3.0; then
    if [ -e /usr/share/gnome-shell/theme/zorin.css ]
    then
      update-alternatives --remove gdm3.css \
        /usr/share/gnome-shell/theme/zorin.css || true
    fi
  fi
fi

#DEBHELPER#
